dnsconf:
    - name: ""
      ipv4:
        enable: true
        gettype: url
        url: https://myip.ipip.net, https://ddns.oray.com/checkip, https://ip.3322.net, https://4.ipw.cn, https://v4.yinghualuo.cn/bejson
        netinterface: eth0
        cmd: ""
        domains:
            - opn.noirprime.com
      ipv6:
        enable: true
        gettype: url
        url: https://speed.neu6.edu.cn/getIP.php, https://v6.ident.me, https://6.ipw.cn, https://v6.yinghualuo.cn/bejson
        netinterface: eth0
        cmd: ""
        ipv6reg: ""
        domains:
            - opn6.noirprime.com
      dns:
        name: cloudflare
        id: ""
        secret: "${CLOUDFLARE_DNS_API}"
      ttl: ""
user:
    username: admin
    password: $2a$10$kwEbs2cthrIKFvQpyjmX9.MNcj3NwavnQ2A/XEvdv9j1.s065ASz2
webhook:
    webhookurl: ""
    webhookrequestbody: ""
    webhookheaders: ""
notallowwanaccess: true
lang: zh