---
# vyos-tasks:interfaces
- name: config interface WAN pppoe
  vyos.vyos.vyos_config:
    lines:
      - set interfaces ethernet eth0 description 'WAN'
      - set interfaces pppoe pppoe0 description 'WAN pppoe'
      - set interfaces pppoe pppoe0 authentication username {{ isp_auth_user }}
      - set interfaces pppoe pppoe0 authentication password {{ isp_auth_pass }}
      - set interfaces pppoe pppoe0 source-interface 'eth0'
      - set interfaces pppoe pppoe0 ipv6 address autoconf

- name: config interface LAN 
  vyos.vyos.vyos_config:
    lines:
      - set interfaces ethernet eth1 description 'LAN'
      - set interfaces ethernet eth1 address '10.0.0.12/24'
      - set service router-advert interface eth1 link-mtu '1492'
      - set service router-advert interface eth1 name-server '2606:4700:4700::1111'
      - set service router-advert interface eth1 name-server '2606:4700:4700::1001'
      - set service router-advert interface eth1 prefix ::/64 valid-lifetime '172800'

- name: config interface BOND
  vyos.vyos.vyos_config:
    lines:
      - set interfaces bonding bond0 mode 802.3ad
      - set interfaces bonding bond0 hash-policy layer2+3
      - set interfaces ethernet eth2 bond group bond0
      - set interfaces ethernet eth3 bond group bond0

- name: config VLAN for BOND
  vyos.vyos.vyos_config:
    lines:
      - set interfaces bonding bond0 vif 1 address 10.0.0.2/24
      - set interfaces bonding bond0 vif 10 address 10.0.10.2/24
      - set interfaces bonding bond0 vif 100 address 10.10.0.2/24
      - set interfaces bonding bond0 vif 200 address 10.20.0.2/24
      - set interfaces bonding bond0 vif 210 address 10.21.0.2/24