---
# vyos-tasks:services-monitoring
- name: config DHCP-Server defaults
  vyos.vyos.vyos_config:
    lines:
      - set service monitoring prometheus node-exporter listen-address 10.0.10.2
      - set service monitoring prometheus node-exporter port 9100
      - set service monitoring prometheus node-exporter collectors textfile

      - set service monitoring prometheus blackbox-exporter listen-address 10.0.10.2
      - set service monitoring prometheus blackbox-exporter port 9101
      - set service monitoring prometheus blackbox-exporter modules dns name dns4 preferred-ip-protocol ip4
      - set service monitoring prometheus blackbox-exporter modules dns name dns4 query-name www.cloudflare.com
      - set service monitoring prometheus blackbox-exporter modules dns name dns4 query-type A

      - set service monitoring prometheus frr-exporter listen-address 10.0.10.2
      - set service monitoring prometheus frr-exporter port 9102