modules:
  icmp_ipv4:
    prober: icmp
    timeout: 5s
    icmp:
      preferred_ip_protocol: "ip4"
      ip_protocol_fallback: false

  icmp_ipv6:
    prober: icmp
    timeout: 5s
    icmp:
      preferred_ip_protocol: "ip6"
      ip_protocol_fallback: false

  dns_ipv4:
    prober: dns
    timeout: 5s
    dns:
      query_name: "example.net"
      query_type: "A"
      transport_protocol: "udp"
      preferred_ip_protocol: "ip4"
      ip_protocol_fallback: false

  dns_ipv6:
    prober: dns
    timeout: 5s
    dns:
      query_name: "example.net"
      query_type: "AAAA"
      transport_protocol: "udp"
      preferred_ip_protocol: "ip6"
      ip_protocol_fallback: false